-- =====================================================================
-- 390  Home route fix + "My" menu group folded into the Home page
--
-- CHANGE REQUEST 2026-09-27
-- -------------------------
--   1. After sign-in Home opens at /Practice, but the Home menu item
--      navigates to /Practice/Index, which answers Page Not Found.
--   2. The "My Notification" menu group (My Notifications, My Practices,
--      My Tasks, My Approvals, My Acknowledgements) is folded into the
--      Home page as a personal "My work" area. The separate group leaves
--      the sidebar; no page, route, API or permission is removed.
--
-- ROOT CAUSE OF (1)
-- -----------------
--   The Home row's menu_url is 'Practice/Index'. _PracticeMenuTree emits
--   it literally as /Practice/Index. Program.cs registers the explicit
--   route "Practice/{areaKey?}" (practice-management-home) BEFORE the
--   default route, so /Practice/Index binds areaKey = "Index" and
--   PracticeController.ShowArea("Index") finds no screen -> 404.
--   Every other menu URL has three segments (Practice/Index/<area>) and
--   reaches the default route, which is why only Home broke.
--
--   Fixed at both ends:
--     * DATA (this file): menu_url 'dashboard' -- the token
--       _PracticeMenuTree.NormalizeMenuUrl already maps to
--       Url.Action("Index", "Practice"), i.e. the canonical /Practice
--       generated by the routing table. Same URL sign-in lands on.
--     * ROUTING (Program.cs): practice-management-home no longer lets
--       areaKey be the literal action name "Index", so a bookmarked or
--       typed /Practice/Index falls through to the default route
--       (controller=Practice, action=Index, no areaKey) -> Home.
--
-- WHY NOT status = 'Inactive' FOR THE "MY" ROWS
-- ---------------------------------------------
--   menu_master.status is BOTH the sidebar filter AND the permission
--   filter: PracticeAuthenticationService loads grants with
--   "m.status = 'Active'", and PracticeController.ShowArea /
--   ShowPracticeArea refuse a screen the caller has no VIEW grant on.
--   Setting the My rows Inactive (the 279/288/289 pattern) would
--   therefore also take My Notifications and My Acknowledgements away
--   from every database user -- the Home page's "View all" links would
--   land on Access Denied.
--
--   So navigation visibility gets its own column:
--     menu_master.show_in_sidebar BIT NOT NULL DEFAULT 1
--   read by the menu-master query and applied ONLY when the sidebar tree
--   is built (PracticeMenuService). Status, grants, the Role Menu
--   Permission matrix and screen access are untouched.
--
-- WHAT THIS DOES
-- --------------
--   1. menu_master.show_in_sidebar (default 1 -- every existing row keeps
--      showing).
--   2. 'dashboard' menu_url -> 'dashboard'.
--   3. show_in_sidebar = 0 for 'my-notifications' and EVERY row beneath
--      it (recursive on parent_menu_id), so a child added directly in a
--      database (e.g. a 'My Tasks' row) is covered without naming it.
--
-- ALSO EDITED: 274_menu_master_seed.sql (authoritative MERGE snapshot):
--   dashboard url, and the same show_in_sidebar step, or its next run
--   would reset them.
--
-- Re-runnable: yes. ASCII-only.
-- Rollback: 390_home_route_and_my_work_on_home_rollback.sql
-- DEPENDS ON: 022 (menu_master), 052 (parent_menu_id), 384.
-- =====================================================================
SET NOCOUNT ON;
SET NOEXEC OFF;
GO

DECLARE @ok BIT = 1;
IF OBJECT_ID('grac_practice.menu_master','U') IS NULL
BEGIN PRINT 'ABORT (390): grac_practice.menu_master missing (run 022).'; SET @ok = 0; END
IF COL_LENGTH('grac_practice.menu_master','parent_menu_id') IS NULL
BEGIN PRINT 'ABORT (390): menu_master.parent_menu_id missing (run 052).'; SET @ok = 0; END
IF @ok = 0
BEGIN
    RAISERROR('390_home_route_and_my_work_on_home: prerequisites missing.', 16, 1);
    SET NOEXEC ON;
END
GO

-- 1. Navigation visibility, separate from status/permissions ------------
IF COL_LENGTH('grac_practice.menu_master','show_in_sidebar') IS NULL
    ALTER TABLE grac_practice.menu_master
        ADD show_in_sidebar BIT NOT NULL
            CONSTRAINT df_pm_menu_show_in_sidebar DEFAULT 1;
GO
PRINT '390: menu_master.show_in_sidebar ready.';
GO

-- 2. Home -> canonical /Practice ----------------------------------------
UPDATE grac_practice.menu_master
   SET menu_url   = N'dashboard',
       updated_by = N'390',
       updated_dt = SYSUTCDATETIME()
 WHERE menu_key = N'dashboard'
   AND ISNULL(menu_url, N'') <> N'dashboard';
PRINT '390: Home menu_url set to dashboard (rows = ' + CAST(@@ROWCOUNT AS NVARCHAR(10)) + ').';
GO

-- 3. "My" group leaves the sidebar (whole subtree) ----------------------
;WITH my_tree AS (
    SELECT menu_id
      FROM grac_practice.menu_master
     WHERE menu_key = N'my-notifications'
    UNION ALL
    SELECT c.menu_id
      FROM grac_practice.menu_master c
      JOIN my_tree p ON c.parent_menu_id = p.menu_id
)
UPDATE m
   SET show_in_sidebar = 0,
       updated_by      = N'390',
       updated_dt      = SYSUTCDATETIME()
  FROM grac_practice.menu_master m
  JOIN my_tree t ON t.menu_id = m.menu_id
 WHERE m.show_in_sidebar = 1;
PRINT '390: My group rows hidden from the sidebar = ' + CAST(@@ROWCOUNT AS NVARCHAR(10)) + '.';
GO

-- Verification ----------------------------------------------------------
SELECT '390-a Home url' AS [check], menu_url,
       CASE WHEN menu_url = N'dashboard' THEN 'PASS' ELSE 'FAIL' END AS result
  FROM grac_practice.menu_master WHERE menu_key = N'dashboard';

SELECT '390-b hidden from sidebar (still Active, grants kept)' AS [check],
       m.menu_key, m.menu_name, m.status, m.show_in_sidebar,
       (SELECT COUNT(*) FROM grac_practice.organization_role_menu_permission p
         WHERE p.menu_id = m.menu_id AND p.status = N'Active') AS active_grants
  FROM grac_practice.menu_master m
 WHERE m.show_in_sidebar = 0
 ORDER BY m.display_order;
GO
SET NOEXEC OFF;
GO
