<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\ControlManagement\src\ControlManagement.Security\ControlManagement.Security.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BrowserLinkEnabled>false</BrowserLinkEnabled>
    <UseBrowserLink>false</UseBrowserLink>
    <IsAspNetCoreBrowserRefreshEnabled>false</IsAspNetCoreBrowserRefreshEnabled>
  </PropertyGroup>

</Project>
